# High purity, bad sync - template-maker

### INTERCALIBRATION RUN @ 100 GeV

#python scripts/submitBatch.py -r 14918 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP_C3.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #C3 
#python scripts/submitBatch.py -r 14982 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v fitHP -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #C2
#python scripts/submitBatch.py -r 14983 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #D2
#python scripts/submitBatch.py -r 14984 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #D3
python scripts/submitBatch.py -r 14985 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP_D4.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #D4
#python scripts/submitBatch.py -r 14987 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #C4
#python scripts/submitBatch.py -r 14988 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #B4
python scripts/submitBatch.py -r 14989 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP_B3.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #B3
#python scripts/submitBatch.py -r 14990 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #B3
#python scripts/submitBatch.py -r 14991 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP_B1.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #B1
#python scripts/submitBatch.py -r 14992 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #C1
#python scripts/submitBatch.py -r 14999 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #D1
#python scripts/submitBatch.py -r 15000 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #E1
#python scripts/submitBatch.py -r 15001 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #E2
#python scripts/submitBatch.py -r 15002 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #E3
python scripts/submitBatch.py -r 15003 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP_E4.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #E4
#python scripts/submitBatch.py -r 15004 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #E5
#python scripts/submitBatch.py -r 15005 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #A1
#python scripts/submitBatch.py -r 15006 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #A2
python scripts/submitBatch.py -r 15007 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP_A3.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #A3
#python scripts/submitBatch.py -r 15008 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #A4
#python scripts/submitBatch.py -r 15009 -c cfg/ECAL_H4_Oct2021/ECAL_H4_Phase2_templates_HP.cfg -v templates -s /eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/ECALTB_H4_Oct2021/HighPurity/ --notar  --spills-per-job 1 -q tomorrow #A5
